public class FacilityFromAcm {
        public String FACILITYID { get; set; }
        public String FACILITYPRODUCT { get; set; }
        public String FACILITYPRODUCTDESCRIPTION { get; set; }
        public String FACILITYACTIVE { get; set; }
        public String CPTYID { get; set; }
        public Decimal TENORVALUE { get; set; }
        public String TENORUNIT { get; set; }
        public String BANKRISKTAKER { get; set; }
        public String STARTDATE { get; set; }
        public String EXPIRYDATE { get; set; }
        public String FACILITYCURRENCY { get; set; }
        public Decimal FACILITYAMOUNT { get; set; }
        public String PARENTFACILITYID { get; set; }
        public String LOSSGIVENDEFAULT { get; set; }
        public String MODIFIEDTIMESTAMP { get; set; }
        public String MODIFIEDBY { get; set; }
    	public String BANKAPPLICATIONKEY { get; set; }
}