/**
* @author Deloitte
* @date 2015
*
* @group Unit Tests
*
* @description Unit Tests Helper - DataFactoryFacade
*/
@isTest
public class ZZTEST_DataFactoryFacade {

    public static ZZTEST_F_User user {get {return ZZTEST_F_User.getInstance();} private set;}

    public static ZZTEST_F_Account account {get {return ZZTEST_F_Account.getInstance();} private set;}

    public static ZZTEST_F_Contact contact {get {return ZZTEST_F_Contact.getInstance();} private set;}

    public static ZZTEST_F_Product product {get {return ZZTEST_F_Product.getInstance();} private set;}
    
    public static ZZTEST_F_Product_Level_2 productLvl2 {get {return ZZTEST_F_Product_Level_2.getInstance();} private set;}
    
    public static ZZTEST_F_Product_Level_3 productLvl3 {get {return ZZTEST_F_Product_Level_3.getInstance();} private set;}

    public static ZZTEST_F_Opportunity opportunity {get {return ZZTEST_F_Opportunity.getInstance();} private set;}
    
    public static ZZTEST_F_OpportunityLineItem opportunityLineItem {get {return ZZTEST_F_OpportunityLineItem.getInstance();} private set;}

    public static ZZTEST_F_PricebookEntry pricebookEntry {get {return ZZTEST_F_PricebookEntry.getInstance();} private set;}

    public static ZZTEST_F_Call_Report callReport {get {return ZZTEST_F_Call_Report.getInstance();} private set;}

    public static ZZTEST_F_JLOC jloc {get {return ZZTEST_F_JLOC.getInstance();} private set;}

    public static ZZTEST_F_Program program {get {return ZZTEST_F_Program.getInstance();} private set;}

    public static ZZTEST_F_Initiative initiative {get {return ZZTEST_F_Initiative.getInstance();} private set;}

    public static ZZTEST_F_Committee committee {get {return ZZTEST_F_Committee.getInstance();} private set;}

    public static ZZTEST_F_Meeting meeting {get {return ZZTEST_F_Meeting.getInstance();} private set;}

    public static ZZTEST_F_Agenda agenda {get {return ZZTEST_F_Agenda.getInstance();} private set;}

    public static ZZTEST_F_Action action {get {return ZZTEST_F_Action.getInstance();} private set;}

    public static ZZTEST_F_Day1Template day1Template {get {return ZZTEST_F_Day1Template.getInstance();} private set;}
    
    public static ZZTEST_F_OpportunitySplit opportunitySplit {get {return ZZTEST_F_OpportunitySplit.getInstance();} private set;}

    public static ZZTEST_F_PricingGroup pricingGroup {get {return ZZTEST_F_PricingGroup.getInstance();} private set;}

    public static ZZTEST_F_PricingTemplate pricingTemplate {get {return ZZTEST_F_PricingTemplate.getInstance();} private set;}

    public static ZZTEST_F_PricingDealProduct pricingDealProduct {get {return ZZTEST_F_PricingDealProduct.getInstance();} private set;}

    public static ZZTEST_F_MatrixLead matrixLead {get {return ZZTEST_F_MatrixLead.getInstance();} private set;}

    public static ZZTEST_F_Roles Roles {get {return ZZTEST_F_Roles.getInstance();} private set;}

}