Opportunity Name,Type,Lead Source,Deal Value Currency,Deal Value,Close Date (Expected Revenue Flow Start),AccountName,Stage,Describtion ,OwnerID
University of Soekmekarr,New to Bank,Sale to Existing Client,ZAR,10000,2017-07-29,Oxford,Opportunity Identified,Overdraft Facility required for Tender,00524000002lLm2AAE
University of Sandton,New to Bank,Other,ZAR,75000,2017-07-29,University of Chigago,Client Engaged,Overdraft Facility required for Tender,00524000002lLmHAAU
RZ IT Expets ,Upsell,Sale to Existing Client,ZAR,1000000,2017-07-29,University of Chigago,Initial Solution Proposed,Overdraft Facility required for Tender,00524000002lLwRAAU
Sizwe Security Company,New to Bank,Sale to Existing Client,EGP,50000,2017-07-29,MMM Global,Client Engaged,Overdraft Facility required for Tender,00524000002lNQ3AAM
Benz,Retention,Sale to Existing Client,ZAR,3000000,2017-07-29,Aygo,Contracts Finalised,Overdraft Facility required for Tender,00524000002lNQwAAM
Shoprite,Retention,Sale to Existing Client,KES,25000000,2017-07-29,Santam,Opportunity Identified,Overdraft Facility required for Tender,00524000001tnUcAAI
Makharm,Retention,Sale to Existing Client,ZAR,60500000,2017-07-29,University of America,Opportunity Identified,Overdraft Facility required for Tender,00524000001toTuAAI
Motor Machanic ,New to Bank,Sale to Existing Client,ZAR,1200000,2017-07-29,Ekurhuleni Metropolitan Municipality,Closed Won,Overdraft Facility required for Tender,00524000001toUdAAI
Suzuki ,New to Bank,Referred by Client,ZAR,200000,2017-07-29,Toyota,Initial Solution Proposed,Overdraft Facility required for Tender,00524000001toUsAAI
Deposit Opportunity,New to Bank,Sale to Existing Client,ZAR,400000,2017-07-29,Banco Itau BBA SA Brazil,Initial Solution Proposed,Overdraft Facility required for Tender,00524000001toVMAAY
